first homework
AntonioB25/android-vjestina-tmdb pull request #1
Opened 2022-04-07 12:19 UTC by AntonioB25

Kasno sam vidio da i kod prikaza detalja treba biti prisutan bottom navigation, tako da bi se topbar i bottombar možda mogli izdvojiti u MainScreen, a onda samo mijenjati sadržaj u sredini. Tako da će vjerojatno trebati izmijeniti navigatore.

Ostale stvari, vezane uz izgled, koje bi se trebale popraviti:
- ikona zvjezdice kod detaljnog prikaza ne radi (mislim da je problem u ikonama)
- User score indikator nije dovršen 
- Poravnanja komponenti

2022-04-11 09:41 UTC, anvukelic reviewed
Go through the all comments - address them either with a change in the code or with the comment and explanation of why it should not be addressed in the code.

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/components/MovieDetails.kt
> +            Spacer(Modifier.padding(10.dp))
For Spacer in:
- Row - Modifier.width(x.dp)
- Column - Modifier.height(x.dp)

That makes spacers easier to read

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/components/MovieDetails.kt
> +fun ImageAndInfo() {
You'll need to pass parameters here and use them in the component

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/components/MovieDetails.kt
> +        text = "Overview",
extract text to strings

Please check all files for this

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/components/MovieDetails.kt
> +    Text(
Check comment on a theme that I've left in the MainActivity and try to create reusable custom components

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/components/MovieDetails.kt
> +     * Trenutno imam samo listu stringova, nisam htio raditi posebnu klasu za osobe
English :)

You've already created CastMember - please use it here

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/components/MovieDetails.kt
> +                fontSize = 20.sp,
font sizes also should go to dimens file

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/components/MovieDetails.kt
> +//    LazyVerticalGrid(
Use `FlowRow` instead

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/components/MovieDetails.kt
> +                    //TODO: show full cast & crew
This is how you're showing to the reviewer that you are aware of something that needs to be implemented

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/components/MovieDetails.kt
> +fun movdetPreviews() {
This is still Composable function so it should start with uppercase

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/components/PopularList.kt
> +                MovieItem(1, "Ironman", R.drawable.ironman),
ID should always be unique - use it in the hardcoded lists too so you don't get some weird issues because of the same ID

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/components/ReccomendationCard.kt
> +
unnecessary extra line

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/components/ReviewCard.kt
> +
Empty line - please check all composable function for this

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/components/ReviewCard.kt
> +            )
reformat code - wrong indention

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/components/SearchBar.kt
> +    var inputText by remember { mutableStateOf("") }
you don't need this here because you have parameters `text` and `onTextChange`
You will define that in the composable above or in the ViewModel and then just use it here.

That is called [State hoisting](https://developer.android.com/jetpack/compose/state#state-hoisting)

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/components/SearchBar.kt
> +                    )
reformat code - check on the internet for a combination of keys. 

Also, there is a checkbox in the commit window in Android Studio to do reformat and optimize imports on all changed files

![image](https://user-images.githubusercontent.com/3305587/162709568-f4e0ffd8-72a2-4adb-80e9-1020f8686ed2.png)

I recommend using reformat manually to get that routine of doing it every time when you see that something is out of order

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/components/SearchBar.kt
> +
too many extra lines :)

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/screens/DetailsScreen.kt
> +}
At the end of every class, there should be an empty space.

You can configure Android Studio to do that instead of you - [link](https://stackoverflow.com/questions/24093609/how-can-i-configure-android-studio-to-add-new-line-at-end-of-file#:~:text=Yes%2C%20you%20can%20configure%20Android,end%20on%20Save%20option%20box.)

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/screens/HomeScreen.kt
> +            Box(
Extract to component

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/screens/HomeScreen.kt
> +
empty lines - please check all files :)

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/screens/HomeScreen.kt
> +    androidx.compose.material.BottomNavigation(
optimize import

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/screens/MainScreen.kt
> +    Scaffold() {
empty parentheses, empty lines

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/screens/MainScreen.kt
> +fun MainNavigationGraph(navController: NavHostController, navigateToDetails: (Int?) -> Unit) {
This could be the first Composable function called in the MainActivity - Main Screen is unnecessary

Also, there is no need to define `navController` and `navigateToDetails` outside of this function - those are probably not gonna be used in the higher layers

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/theme/Theme.kt
>  private val LightColorPalette = lightColors(
You have defined palettes but I still see that you're using colors like `DarkBlue` in some components.

You should always use colors from the theme

2022-04-11 09:41 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/ui/theme/Type.kt
>  val Typography = Typography(
use this to create reusable text components

2022-04-11 09:42 UTC, anvukelic requested changes
Address comments

2022-04-13 22:50 UTC, AntonioB25 commented on app/src/main/java/com/e/tmdb/ui/components/MovieDetails.kt
> +    LazyColumn() {
I had a problem with scrolling (two scrollables in the same direction). I was trying different things, so in the end, I used LazyColum because I knew it was scrollable. I forgot to try vertical scroll modifier on the Column. 
I will change it to Column and set modifier.

2022-04-13 22:52 UTC, AntonioB25 commented on app/src/main/java/com/e/tmdb/ui/components/MovieDetails.kt
> +//    LazyVerticalGrid(
Isn't FlowRow deprecated? I did try to use it, but couldn't. [link](https://android-review.googlesource.com/c/platform/frameworks/support/+/1521704)

2022-09-28 16:57 UTC, merged