Homework third
AntonioB25/android-vjestina-tmdb pull request #4
Opened 2022-05-14 10:37 UTC by AntonioB25

Third homework

I get movies and show them. Home screen is working.
Images need fixing in movie details.
Problem is probably in MovieDetailsViewModel.

2022-05-19 11:40 UTC, anvukelic requested changes
Small changes are required, ping me once you address them - also, check second PR for the comments since I left some comments there but they are also applicable here

2022-05-19 11:40 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/respository/MovieDetailsRepository.kt
> +        return flowOf(movieApi.getMovieDetails(movieId).toMovieDetails())
it would be better if you call movieApi.fetchMovieDetails() - this way, you're saying map MovieDetails to MovieDetails

2022-05-19 11:40 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/respository/MovieRepository.kt
> +    override suspend fun getPopularMovies(): Flow<List<Movie>> {
if you're returning flow, there is no need for a function to be suspended

2022-05-19 11:40 UTC, anvukelic commented on app/src/main/java/com/e/tmdb/viewModel/HomeViewModel.kt
> +        return popular
check comment from the last PR

2022-05-23 12:39 UTC, AntonioB25 commented on app/src/main/java/com/e/tmdb/respository/MovieRepository.kt
> +    override suspend fun getPopularMovies(): Flow<List<Movie>> {
if I remove `suspended` I get error because `movieApi.getPopularMovies()` is suspended and I cannot remove suspended from `movieApi.getPopularMovies()` because `client.get(url)` is suspended. What should I do?

2022-09-28 16:56 UTC, merged